title: Patton-Tech.com
email: jeffrey@patton-tech.com
description: >- # this means to ignore newlines until "baseurl:"
  Making It Go
#baseurl: "/pattontech" # the subpath of your site, e.g. /blog
url: "https://patton-tech.com" # the base hostname & protocol for your site, e.g. http://example.com
author: "Jeffrey S. Patton"

google_analytics: G-LFBCDLFFLL

show_excerpts: true

paginate: 5
paginate_path: /posts/page:num

include:
  - _pages
  
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.28.0
#remote_theme: jekyll/minima
#theme: minima

minimal_mistakes_skin: dark
# minima:
#   skin: dark
#   social_links:
#     - { platform: twitter,  user_url: "https://twitter.com/jspatton" }
#     - { platform: github,  user_url: "https://github.com/jeffpatton1971/" }
#     - { platform: linkedin,  user_url: "https://www.linkedin.com/in/jeffpatton/" }

#remote_theme: pages-themes/midnight@v0.2.0
#remote_theme: mmistakes/minimal-mistakes

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: pattontech

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache

author:
  name   : "Jeff Patton"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "25 hours a day, 8 days a week, how does he do it?"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://patton-tech.com"
    - label: "Bluesky"
      icon: "fab fa-brands fa-bluesky"
      url: "https://bsky.app/profile/jeffpatton.bsky.social"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jeffpatton1971"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jspatton1971"

defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
