# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Patton-Tech.com
email: jeffrey@patton-tech.com
description: >- # this means to ignore newlines until "baseurl:"
  Making It Go
#baseurl: "/pattontech" # the subpath of your site, e.g. /blog
url: "https://patton-tech.com" # the base hostname & protocol for your site, e.g. http://example.com
author: "Jeffrey S. Patton"
twitter_username: jspatton
github_username:  jeffpatton1971

google_analytics: UA-8275694-2
google_cse_id: bafe326421f6e5ee5

show_excerpts: true

paginate: 5
paginate_path: /posts/page:num

collections:
  authors:
    output: true

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
#theme: minima

minima:
  skin: dark

#remote_theme: pages-themes/midnight@v0.2.0
#remote_theme: mmistakes/minimal-mistakes

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: pattontech

plugins:
  - jekyll-feed
  - jekyll-remote-theme
#  - jekyll-include-cache

gems:
  - jekyll-google_cse
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
